<?php

namespace App\Exports;

use Carbon\Carbon;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use Maatwebsite\Excel\Concerns\FromArray;
use PhpOffice\PhpSpreadsheet\Style\Color;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class CRMAnalyticsExport implements FromArray, WithStyles, WithEvents
{
    protected $data;
    protected $filters;

    public function __construct($data, $filters)
    {
        $this->data = $data;
        $this->filters = $filters;
    }

    public function array(): array
    {
        $rows = [];

        // 🟢 MAIN TITLE - Merge all 9 columns
        $rows[] = ['CRM ANALYTICS DASHBOARD REPORT', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        
        // 🟢 GENERATED INFO
        $rows[] = ['Generated On:', $this->filters['generated_at'] ?? now()->format('d M Y h:i A'), '', '', '', '', '', '', ''];
        $rows[] = ['Generated By:', auth()->user()->name ?? 'System', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];

        // 🟢 FILTERS SECTION
        $rows[] = ['📊 FILTERS APPLIED', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        
        $rows[] = ['Date Range', ':', ($this->filters['start_date'] ?? '-') . ' to ' . ($this->filters['end_date'] ?? '-'), '', '', '', '', '', '', ''];
        $rows[] = ['Department', ':', $this->filters['department'] ?? 'All Departments', '', '', '', '', '', '', ''];
        $rows[] = ['Pipeline', ':', ucfirst($this->filters['pipeline'] ?? 'All Pipelines'), '', '', '', '', '', '', ''];
        $rows[] = ['Status', ':', \App\Utils\crm_status_label($this->filters['status'] ?? 'all', 'all_Status'), '', '', '', '', '', '', ''];
        $rows[] = ['Message Type', ':', ucfirst($this->filters['message_type'] ?? 'All Types'), '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];

        // 🟢 SUMMARY STATISTICS SECTION
        if (isset($this->filters['summary'])) {
            $summary = $this->filters['summary'];
            $total = $summary['total'] ?? 0;
            $assigned = $summary['assigned'] ?? 0;
            $pending = $summary['pending'] ?? 0;
            $converted = $summary['converted'] ?? 0;
            $ignored = $summary['ignored'] ?? 0;
            $spam = $summary['spam'] ?? 0;
            
            $assignedPercentage = $total > 0 ? round(($assigned / $total) * 100, 1) . '%' : '0%';
            $convertedPercentage = $total > 0 ? round(($converted / $total) * 100, 1) . '%' : '0%';
            $pendingPercentage = $total > 0 ? round(($pending / $total) * 100, 1) . '%' : '0%';
            
            $rows[] = ['📈 SUMMARY STATISTICS', '', '', '', '', '', '', '', ''];
            $rows[] = ['', '', '', '', '', '', '', '', ''];
            
            $rows[] = ['Total Messages', $total, '100%', '', '', '', '', '', ''];
            $rows[] = ['Assigned', $assigned, $assignedPercentage, '', '', '', '', '', ''];
            $rows[] = ['Pending', $pending, $pendingPercentage, '', '', '', '', '', ''];
            $rows[] = ['Converted', $converted, $convertedPercentage, '', '', '', '', '', ''];
            $rows[] = ['Ignored', $ignored, round(($ignored / max($total, 1)) * 100, 1) . '%', '', '', '', '', '', ''];
            $rows[] = ['Spam', $spam, round(($spam / max($total, 1)) * 100, 1) . '%', '', '', '', '', '', ''];
            $rows[] = ['', '', '', '', '', '', '', '', ''];
            $rows[] = ['Assignment Rate', $assignedPercentage, '', '', '', '', '', '', ''];
            $rows[] = ['Conversion Rate', $convertedPercentage, '', '', '', '', '', '', ''];
            $rows[] = ['', '', '', '', '', '', '', '', ''];
            $rows[] = ['', '', '', '', '', '', '', '', ''];
        }

        // 🟢 DAILY BREAKDOWN HEADER
        $rows[] = ['📅 DAILY BREAKDOWN REPORT', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        $rows[] = [
            'Date',
            'Total',
            'Assigned',
            'Pending',
            'Converted',
            'Ignored',
            'Spam',
            'Assignment %',
            'Conversion %'
        ];

        // 🟢 DATA ROWS
        foreach ($this->data as $row) {
            $assignedPercentage = $row->total > 0 
                ? round(($row->assigned / $row->total) * 100, 1) . '%' 
                : '0%';
                
            $convertedPercentage = $row->total > 0 
                ? round(($row->converted / $row->total) * 100, 1) . '%' 
                : '0%';
                
            $rows[] = [
                Carbon::parse($row->date)->format('d M Y'),
                (int) ($row->total ?? 0),
                (int) ($row->assigned ?? 0),
                (int) ($row->pending ?? 0),
                (int) ($row->converted ?? 0),
                (int) ($row->ignored ?? 0),
                (int) ($row->spam ?? 0),
                $assignedPercentage,
                $convertedPercentage
            ];
        }

        // 🟢 GRAND TOTAL ROW
        if (count($this->data) > 0) {
            $rows[] = ['', '', '', '', '', '', '', '', ''];
            $rows[] = [
                'GRAND TOTAL',
                (int) $this->data->sum('total'),
                (int) $this->data->sum('assigned'),
                (int) $this->data->sum('pending'),
                (int) $this->data->sum('converted'),
                (int) $this->data->sum('ignored'),
                (int) $this->data->sum('spam'),
                $this->data->sum('total') > 0 ? round(($this->data->sum('assigned') / $this->data->sum('total')) * 100, 1) . '%' : '0%',
                $this->data->sum('total') > 0 ? round(($this->data->sum('converted') / $this->data->sum('total')) * 100, 1) . '%' : '0%'
            ];
        }

        // 🟢 FOOTER
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        $rows[] = ['', '', '', '', '', '', '', '', ''];
        $rows[] = ['* This report is auto-generated from CRM Analytics Dashboard', '', '', '', '', '', '', '', ''];
        $rows[] = ['* Report Period: ' . ($this->filters['start_date'] ?? '-') . ' to ' . ($this->filters['end_date'] ?? '-'), '', '', '', '', '', '', '', ''];
        $rows[] = ['* Generated on: ' . now()->format('d M Y h:i:s A'), '', '', '', '', '', '', '', ''];

        return $rows;
    }

    public function styles(Worksheet $sheet)
    {
        return [
            // Style the title row
            1 => [
                'font' => [
                    'bold' => true,
                    'size' => 18,
                    'color' => ['rgb' => '2C3E50'],
                ],
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                ],
            ],
        ];
    }

   public function registerEvents(): array
{
    return [
        AfterSheet::class => function(AfterSheet $event) {
            $sheet = $event->sheet->getDelegate();
            
            // Set column widths
            $sheet->getColumnDimension('A')->setWidth(18);
            $sheet->getColumnDimension('B')->setWidth(12);
            $sheet->getColumnDimension('C')->setWidth(12);
            $sheet->getColumnDimension('D')->setWidth(12);
            $sheet->getColumnDimension('E')->setWidth(12);
            $sheet->getColumnDimension('F')->setWidth(12);
            $sheet->getColumnDimension('G')->setWidth(12);
            $sheet->getColumnDimension('H')->setWidth(15);
            $sheet->getColumnDimension('I')->setWidth(15);

            // Find the header row position
            $headerRow = 0;
            foreach ($sheet->getRowIterator() as $row) {
                $cellValue = $sheet->getCell('A' . $row->getRowIndex())->getValue();
                if ($cellValue === 'Date') {
                    $headerRow = $row->getRowIndex();
                    break;
                }
            }

            if ($headerRow > 0) {
                // Style the header row
                $sheet->getStyle('A' . $headerRow . ':I' . $headerRow)->applyFromArray([
                    'font' => [
                        'bold' => true,
                        'color' => ['rgb' => 'FFFFFF'],
                        'size' => 11,
                    ],
                    'fill' => [
                        'fillType' => Fill::FILL_SOLID,
                        'startColor' => ['rgb' => '3498DB'],
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                        'vertical' => Alignment::VERTICAL_CENTER,
                    ],
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_THIN,
                            'color' => ['rgb' => 'FFFFFF'],
                        ],
                    ],
                ]);

                // Style data rows
                $lastRow = $sheet->getHighestRow();
                $dataRange = 'A' . ($headerRow + 1) . ':I' . ($lastRow - 4);
                
                $sheet->getStyle($dataRange)->applyFromArray([
                    'borders' => [
                        'allBorders' => [
                            'borderStyle' => Border::BORDER_THIN,
                            'color' => ['rgb' => 'DDDDDD'],
                        ],
                    ],
                    'alignment' => [
                        'horizontal' => Alignment::HORIZONTAL_CENTER,
                    ],
                ]);

                // Style grand total row
                $totalRow = $lastRow - 4;
                if ($totalRow > $headerRow) {
                    $sheet->getStyle('A' . $totalRow . ':I' . $totalRow)->applyFromArray([
                        'font' => [
                            'bold' => true,
                            'size' => 11,
                        ],
                        'fill' => [
                            'fillType' => Fill::FILL_SOLID,
                            'startColor' => ['rgb' => 'F8F9FA'],
                        ],
                        'borders' => [
                            'top' => [
                                'borderStyle' => Border::BORDER_MEDIUM,
                                'color' => ['rgb' => '3498DB'],
                            ],
                            'bottom' => [
                                'borderStyle' => Border::BORDER_THIN,
                                'color' => ['rgb' => '3498DB'],
                            ],
                        ],
                    ]);
                }

             
            }

            // Style section headers - MERGE ALL 9 COLUMNS
            foreach ($sheet->getRowIterator() as $row) {
                $rowIndex = $row->getRowIndex();
                $cellValue = $sheet->getCell('A' . $rowIndex)->getValue();
                
                if (is_string($cellValue) && (
                    strpos($cellValue, '📊') !== false || 
                    strpos($cellValue, '📈') !== false || 
                    strpos($cellValue, '📅') !== false)) {
                    
                    $sheet->mergeCells('A' . $rowIndex . ':I' . $rowIndex);
                    $sheet->getStyle('A' . $rowIndex)->applyFromArray([
                        'font' => [
                            'bold' => true,
                            'size' => 13,
                            'color' => ['rgb' => '2C3E50'],
                        ],
                        'fill' => [
                            'fillType' => Fill::FILL_SOLID,
                            'startColor' => ['rgb' => 'E8F4FD'],
                        ],
                        'alignment' => [
                            'horizontal' => Alignment::HORIZONTAL_LEFT,
                        ],
                    ]);
                }
            }

            // Style the main title - MERGE ALL 9 COLUMNS
            $sheet->mergeCells('A1:I1');
            $sheet->getStyle('A1')->applyFromArray([
                'font' => [
                    'bold' => true,
                    'size' => 20,
                    'color' => ['rgb' => '2C3E50'],
                ],
                'alignment' => [
                    'horizontal' => Alignment::HORIZONTAL_CENTER,
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
            ]);

            // Style generated info rows
            if ($sheet->getCell('A3')->getValue()) {
                $sheet->mergeCells('A3:I3');
            }
            if ($sheet->getCell('A4')->getValue()) {
                $sheet->mergeCells('A4:I4');
            }
            $sheet->getStyle('A3:A4')->getFont()->setBold(true);

            // Set auto-filter (this doesn't affect scrolling)
            if ($headerRow > 0) {
                try {
                    $sheet->setAutoFilter('A' . $headerRow . ':I' . $headerRow);
                } catch (\Exception $e) {
                    // If auto-filter fails, just continue without it
                   
                }
            }

            // Wrap text for better visibility
            $sheet->getStyle('A1:I' . $sheet->getHighestRow())
                ->getAlignment()
                ->setWrapText(true);
        },
    ];
}
}
