<?php

return [

    'dashboard' => ['read'],
    'pos_management' => ['create', 'read', 'update', 'delete'],
    'warranty_section' => [
        'warranty_dashboard',
        'warranty_import',
        'warranty_import_history',
        'warranty_activation_list',
        'warranty_activation_view',
        'warranty_manual_activation',
        'warranty_activation_review',
        'warranty_activation_approve',
        'warranty_activation_reject',
        'warranty_blacklist',
        'warranty_blacklist_add',
        'warranty_blacklist_remove',
        'warranty_report_claims',
        'warranty_report_sla',
        'warranty_report_activations',
        'warranty_serial_transaction',
    ],
    'support_section' => ['create', 'read', 'update', 'delete'],
    'report' => ['read'],
    'user_section' => ['create', 'read', 'update', 'delete'],
    'crm_section' => [
        'dashboard_view',
        'inbox_list',
        'inbox_view',
        'inbox_export',
        'inbox_show_message',
        'inbox_add_new_message',
        'inbox_update_ticket_department',
        'inbox_convert_inquiry',
        'inbox_convert_bulk_inquiry',
        'inbox_update_message_type',
        'inbox_ignore_message',
        'inbox_mark_spam',
        'inbox_assign_employee',
        'inbox_assign_owner',
        'inbox_delete_message',
        'inbox_get_user_info',
        'inbox_connect_user',
        'lead_list',
        'lead_show',
        'lead_view',
        'lead_convert_to_deal',
        'lead_disqualify',
        'lead_assign_employee',
        'lead_assign_owner',
        'lead_assign_department',
        'lead_export',
        'lead_get_user_orders',
        'deal_wholesale_list',
        'deal_wholesale_view',
        'deal_wholesale_request_quotation',
        'deal_wholesale_disqualify',
        'deal_wholesale_assign_employee',
        'deal_wholesale_assign_owner',
        'deal_wholesale_assign_department',
        'deal_wholesale_export',
        'deal_retail_list',
        'deal_retail_view',
        'deal_retail_request_quotation',
        'deal_retail_disqualify',
        'deal_retail_assign_employee',
        'deal_retail_assign_owner',
        'deal_retail_assign_department',
        'deal_retail_export',
        'deal_retail_link_order',
        'deal_retail_get_user_data',
        'ticket_complaint_list',
        'ticket_view',
        'ticket_conversation',
        'ticket_complaint_dashboard',
        'ticket_complaint_update_status',
        'ticket_complaint_reply',
        'ticket_department_update',
        'ticket_employee_update',
        'ticket_support_follow_up',
        'ticket_complain_follow_up',
        'ticket_wholesale_follow_up',
        'support_ticket_list',
        'support_ticket_details',
        'support_ticket_export',
        'support_ticket_update_status',
        'support_ticket_reply',
        'service_ticket_assign',
        'service_ticket_details',
        'service_ticket_create_estimate',
        'service_ticket_schedule',
        'service_ticket_start_job',
        'service_ticket_complete_job',
        'service_ticket_change_order',
        'service_ticket_qa',
        'service_ticket_close',
        'service_ticket_cancel',
        'career_ticket_list',
        'career_ticket_view',
        'career_ticket_update_status',
        'career_ticket_assign_recruiter',
        'career_ticket_screen',
        'career_ticket_schedule_interview',
        'career_ticket_conduct_interview',
        'career_ticket_attach_offer',
        'career_ticket_decline_offer',
        'career_ticket_reject',
        'career_ticket_add_to_talent_pool',
        'career_ticket_export_pool',
        'career_ticket_reply',
        'update_ticket_follow_up',
        'sla_list',
        'sla_create',
        'sla_edit',
        'sla_update',
        'sla_delete',
        'sla_status_toggle',
        'calendar_view',
        'notification_list',
        'notification_view',
        'notification_ticket_conversation',
        'warranty_claim_list',
        'warranty_claim_view',
        'warranty_claim_triage',
        'warranty_claim_approved',
        'warranty_claim_rma',
        'warranty_claim_received',
        'warranty_claim_repair',
        'warranty_claim_resolved',
        'warranty_claim_closed',
        'warranty_claim_rejected',
        'warranty_claim_decide',
        'warranty_claim_receive',
        'warranty_claim_diagnose',
        'warranty_claim_qc',
        'warranty_claim_dispatch',
        'warranty_claim_replacement',
        'warranty_claim_close',
        'warranty_claim_payment',
        'warranty_claim_resume',
        'warranty_claim_resolve',
        'warranty_claim_submit',
        'warranty_claim_export',
        'warranty_claim_review',
        'chat_box_view',
        
    ],
    'system_settings' => ['create', 'read', 'update', 'delete'],
    'cms_management' => ['create', 'read', 'update', 'delete'],
    'order_management' => ['order_list', 'order_view', 'order_branch_assign', 'order_deliverey', 'order_payment_status', 'order_shiping_method', 'order_invoice', 'order_address', 'refund_request_list', 'refund_request_view', 'refund_request_update'],
    'product_management' => ['category_setup', 'sub_category_setup', 'sub_sub_category_setup', 'brand_setup', 'product_attribute_setup', 'product_list', 'product_view', 'product_add', 'product_update', 'product_delete', 'product_status', 'showcase_status', 'product_gallery', 'bulk_import', 'product_make_setup'],
    'promotion_management' => ['banner_setup', 'coupon', 'flash_deals', 'deal_of_the_day', 'featured_deal', 'clearance_sale', 'send_notifications', 'push_notification_setup', 'announcement'],
    'branch_management' => ['add_branch', 'branch_list', 'branch_stock_list', 'branch_view', 'branch_edit', 'branch_delete', 'request_restock_list', 'stock_request_list', 'stock_request_view', 'stock_delivery', 'add_new_stock_request', 'stock_transfer_list', 'transfer_new_stock'],

    'wholesaler_section' => [
        'wholesaler_dashboard',
        'tier_view',
        'tier_add',
        'tier_edit',
        'tier_delete',
        'wholesaler_join_request',
        'wholesaler_view',
        'wholesaler_update',
        'wholesaler_moq_owerride',
        'wholesaler_contact',
        'purchase_request_view',
        'assign_purchase_order_no',
        'create_quotation',
        'purchase_request_delete',
        'quotation_view',
        'assign_quotation_no',
        'quotation_update',
        'quotation_delete',
        'confirme_order_view',
        'assign_confirm_order_no',
        'assign_invoice_no',
        'confirem_order_delivery',
        'confirem_order_payment',
        'confirem_order_invoice',
        'product_add',
        'product_edit',
        'product_view',
        'product_delete',
        'product_list',
        'product_status',
    ],

];
