<script>
    window.crmUiText = Object.assign({}, window.crmUiText || {}, {
        messageTypeUpdatedSuccessfully: @json(translate('Message type updated successfully!')),
        failedToUpdateMessageType: @json(translate('Failed to update message type!')),
        pleaseSelectAtLeastOneMessage: @json(translate('Please select at least one message!')),
        successTitle: @json(translate('Success!')),
        errorTitle: @json(translate('Error') . '!'),
        deletedTitle: @json(translate('Deleted!')),
        notConvertedTitle: @json(translate('Not Converted')),
        noInquiryConverted: @json(translate('No inquiry converted!')),
        somethingWentWrong: @json(translate('Something went wrong!')),
        areYouSure: @json(translate('Are you sure?')),
        ignoreMessagePrompt: @json(translate('Do you want to ignore this message?')),
        yesIgnoreIt: @json(translate('Yes, Ignore it!')),
        cancel: @json(translate('Cancel')),
        markSpamPrompt: @json(translate('Do you want marked spam this message?')),
        yesMarkIt: @json(translate('Yes, marked it!')),
        selectSupervisor: @json(translate('Select Supervisor')),
        loading: @json(translate('Loading...')),
        selectEmployee: @json(translate('Select Employee')),
        notAssigned: @json(translate('Not Assigned')),
        convertButtonText: @json(translate('Convert')),
        convertingText: @json(translate('Converting...')),
        convertLeadMissingMessage: @json(translate('Lead id is missing. Please close and reopen the convert form')),
        convertSelectPartyMessage: @json(translate('Please select a party from search results before converting')),
        selectOrder: @json(translate('Select Order')),
        noOrdersFound: @json(translate('No Orders Found')),
        errorLoadingOrders: @json(translate('Error loading orders')),
        leadDisqualifyPrompt: @json(translate('You want to disqualify this lead!')),
        yesDisqualify: @json(translate('Yes, Disqualify')),
        disqualifiedLabel: @json(translate('Disqualified')),
        escalateWarning: @json(translate('This will notify the department and owner.')),
        yesEscalate: @json(translate('Yes, Escalate')),
        deleteMessagePrompt: @json(translate('This message will be moved to trash!')),
        yesDeleteIt: @json(translate('Yes, delete it!')),
        selectReason: @json(translate('Select Reason')),
        selectSubType: @json(translate('Select Sub-Type')),
        failedToLoadUserInfo: @json(translate('Failed to load user info.')),
        userConnectedSuccessfully: @json(translate('User connected successfully!')),
        requestFailed: @json(translate('Request failed!')),
        genericTryAgain: @json(translate('Something went wrong!')),
        saveTask: @json(translate('Save Task')),
        updateTask: @json(translate('Update Task')),
        markTaskCompletePrompt: @json(translate('Do you want to mark this task as complete?')),
        yesMarkComplete: @json(translate('Yes, mark complete')),
        nameLabel: @json(translate('Name')),
        emailLabel: @json(translate('Email')),
        phoneLabel: @json(translate('Phone')),
        statusLabels: {
            new: @json(translate('New')),
            processing: @json(translate('processing')),
            converted: @json(translate('converted')),
            ignored: @json(translate('ignored')),
            spam: @json(translate('spam')),
        },
        leadSubTypes: [
            { value: 'retail', label: @json(translate('Retail')) },
            { value: 'wholesale', label: @json(translate('Wholesale')) },
        ],
        ticketSubTypes: [
            { value: 'support', label: @json(translate('Support')) },
            { value: 'complaint', label: @json(translate('Complaint')) },
            { value: 'career', label: @json(translate('Career')) },
            { value: 'service', label: @json(translate('Service')) },
            { value: 'retail', label: @json(translate('Retail')) },
            { value: 'wholesale', label: @json(translate('Wholesale')) },
        ],
        inquiryReasons: [
            { value: 'complaint', label: @json(translate('Complaint')) },
            { value: 'delivery_issue', label: @json(translate('delivery_issue')) },
            { value: 'return_rma', label: @json(translate('return_rma')) },
            { value: 'billing_refund', label: @json(translate('billing_refund')) },
            { value: 'product_issue_defect', label: @json(translate('product_issue_defect')) },
            { value: 'setup_how_to', label: @json(translate('setup_how_to')) },
            { value: 'general_inquiry', label: @json(translate('general_inquiry')) },
        ],
    });
</script>
